### PR TITLE
Final antipiracy check identified

### PR DESCRIPTION
**Pull request by lilliththecreative**
Identified UNKNOWN_C3FDC5.

### CODE REVIEW

**Comment by Herringway** [comment]
At the moment, I can't really accept any assembly changes for reasons that should become very obvious very soon. I promise I'm not ignoring this right now.

**Comment by lilliththecreative** [comment]
Are you reverse engineering the C code?

**Comment by Herringway** [comment]
that's not wrong, but it isn't right either. it should be finished in the next few days

**Comment by lilliththecreative** [comment]
Is it alright if I make an issue with the things I've identified so you can
add them in when convenient?

**Comment by Herringway** [comment]
Sure. leave out anything that's already documented in [the port](https://github.com/Herringway/earthbound)

**Comment by Herringway** [comment]
Taken care of by 5314ae74a0a4aab99d551ef14f599f7be7ab320e

**Pull request closed without merging**
